ZENG-172934 - GitHub: create ispw-generate action to call generate-await REST API in CES
https://zsojira.bmc.com/browse/ZENG-172934

Squashed Previous commits:
* error not defined properly - added logging
* problem with utils
* Error: taskResponse is not defined
* change to http
* post request is done asynchronously
* ReferenceError: outputData is not defined
* add outputs
* change error handling
* Error: Cannot find module '@actions/core'
* make api request synchronous
* make logging wait for response
* add tests
* UnhandledPromiseRejectionWarning
* Error: Cannot read property 'generateFailedCount' of undefined
* Error: responseBody.awaitStatus.statusMsg.join is not a function
* add finally clause
* fix message concatenation
* Error: responseBody.awaitStatus.statusMsg.forEach is not a function
* successful case should be good now
* update program flow
* outputs should be available now
* ReferenceError: cesUrl is not defined
* Error: TypeError: Cannot read property 'toString' of undefined
* ReferenceError: requestUrl is not defined
* get rid of debug logging
* outputs not defined correctly
* updated doc
* added tests
* added javascript doc